### PR TITLE
Feature/seek bar row

### PR DESCRIPTION
**Pull request by xgouchet**
Allow users to add a seekbar in the form : 

```
            section("Section 3") {
                id = 6
                seekBarRow {
                    id = 7
                    title = "Slider row"
                    maxValue = 42
                    value = 33
                }
            }
```

### CODE REVIEW

**Comment by florent37** [comment]
Thanks, i will message you tomorrow to talk About AbstractTextRow for me it's a row with text on the left

**Comment by xgouchet** [comment]
Oh ok, in that case maybe use title instead of text? At all rate I think it should be in its own source file.

**Comment by xgouchet** [comment]
Oh ok, in that case maybe use title instead of text? At all rate I think it should be in its own source file.

**Comment by florent37** [comment]
Yes, title Has more meaning than text in this case

Le 15 févr. 2018 18:34, "Xavier F. Gouchet" <notifications@github.com> a
écrit :

**Comment by xgouchet** [comment]
Updated, renaming it to AbstractTitleRow

**Comment by florent37** [comment]
Thanks 👍

**Pull request merged**
